Are are only allowed 5 keywords per crate.
cargo publish said:

error: failed to publish to registry at https://crates.io

Caused by:
  the remote server responded with an error (status 400 Bad Request): expected at most 5 keywords per crate